feat(Markup): add pagnation components file structure
HyperFunctor/next-paginate pull request #3
Opened 2022-04-12 05:40 UTC by dziekonskik

- created two base components - basic pagination (Pagination) and pagination with interactive dots (DottedPagination), my idea is that the user will be able to import either of those.
- created helper components: PaginationArray , PaginationItem, PaginationDots

2022-04-12 16:06 UTC, mmiszy requested changes

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationArray.tsx
> +    case 2 || 3:
```suggestion
    case 2:
    case 3:
```

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationArray.tsx
> +    case pagesTotal - 1 || pagesTotal - 2:
```suggestion
    case pagesTotal - 1:
    case pagesTotal - 2:
```

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationArray.tsx
> +  let pages = Array.from(
```suggestion
  const pages = Array.from(
```

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationArray.tsx
> +      }
What does it do?

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationArray.tsx
> +  pages = currentPage === pagesTotal - 1 ? pages.reverse() : pages;
Why?

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationDots.tsx
> +  }, [inputValue, router, path]);
What does it do? Why `document.addEventListener` instead of `onKeyup`?

2022-04-12 16:06 UTC, typeofweb commented on src/PaginationDots.tsx
> +  }
```suggestion
  return condition ? (
    <div onMouseEnter={() => setShowInput(true)}>
      <span>.</span>
      <span>.</span>
      <span>.</span>
    </div>
  ) : null;
```

2022-04-12 18:49 UTC, dziekonskik commented on src/PaginationArray.tsx
> +    case 2 || 3:
will do

2022-04-12 18:49 UTC, dziekonskik commented on src/PaginationArray.tsx
> +    case pagesTotal - 1 || pagesTotal - 2:
will do

2022-04-12 18:50 UTC, dziekonskik commented on src/PaginationArray.tsx
> +  let pages = Array.from(
I cannot because I reuse it later  
pages = currentPage === pagesTotal - 1 ? pages.reverse() : pages;

2022-04-12 18:53 UTC, dziekonskik commented on src/PaginationArray.tsx
> +      }
it decides what numbers should be rendered in pagination apart from the first and last one

2022-04-12 18:56 UTC, dziekonskik commented on src/PaginationArray.tsx
> +  pages = currentPage === pagesTotal - 1 ? pages.reverse() : pages;
because on one before the last page instead of eg. 98 99 100 i get 99 98 100

2022-04-12 18:56 UTC, dziekonskik commented on src/PaginationDots.tsx
> +  }, [inputValue, router, path]);
i can't remember :) perhaps it would be the best to change it ?

2022-04-12 19:49 UTC, mmiszy commented on src/PaginationArray.tsx
> +  pages = currentPage === pagesTotal - 1 ? pages.reverse() : pages;
It should not be part of a component. Should be a function instead.

2022-04-12 19:49 UTC, mmiszy commented on src/PaginationArray.tsx
> +      }
It should not be part of a component. Should be a function instead.

2022-04-12 19:49 UTC, mmiszy commented on src/PaginationArray.tsx
> +  let pages = Array.from(
You must not use `let`.

2022-04-21 18:05 UTC, mmiszy commented on src/PaginationDots.tsx
> +  }, [inputValue, router, path]);
Yes :)

2022-04-22 09:27 UTC, closed without merging